### ISSUE TITLE
Is there an option to see views?

### ISSUE THREAD

**Issue by nagulv** [coleifer/sqlite-web#56]
I would like to see views and their data in the same way.

**Comment by coleifer** [comment]
Not at present.

**Comment by moomoohk** [comment]
Hey Charles
Any plans on adding this feature?

**Comment by moomoohk** [comment]
I've patched a local version of this repo so that views work as intended, however the code is not up to standard so I don't feel comfortable submitting a pull request. I think there's also some work that has to be done on peewee itself for this to work perfectly.

Outline of what I did:

- Override `SqliteDataSet` constructor to pass `include_views=True` to `self._introspector.generate_models` (there's no way to pass the parameter to the parent `DataSet`'s constructor)
- Override `SqliteDataSet.update_cache` for the same reason
- Made `_format_create_table` aware of views and added support for `CREATE VIEW <name> AS <etc>` (requires more complex formatting than `CREATE TABLE`)
- Adapted all `SELECT sql FROM sqlite_master` queries to accommodate cases `WHERE type = 'view'`
- In the `base_tables.html` view I copied the loop that renders tables from `dataset.tables` and iterated over `dataset.views` as well

It's not perfect (some column types are not inferred, might be a peewee issue) but it answers my current needs

Official support would be nice :)

**Comment by yassirlaaouissi** [comment]
sad, would like to see this happen tbh. It is an awesome project :)

**Comment by yassirlaaouissi** [comment]
Okay so basicly there is an option, but it aint pretty. You can ez add views via queries: https://www.sqlitetutorial.net/sqlite-create-view/

And you can view them by executing queries via the Query tab in a table:
![afbeelding](https://user-images.githubusercontent.com/59022605/105607372-86a35880-5d9e-11eb-8c43-ccbd99dbae7e.png)


Roughly the syntax my m8 used was:



```

CREATE VIEW testview
AS
SELECT
    CarTable.insuranceNumber, CarTable.Type, InsuranceTable.clientID, ClientTable.firstName, ClientTable.lastName, ClientTable.Address, ClientTable.postalCode, ClientTable.City, InvoicesTable.Products, InvoicesTable.Services, InvoicesTable.costPrice
FROM
    CarTable
INNER JOIN insuranceNumber ON InsuranceTable.insuranceNumber = CarTable.insuranceNumber
INNER JOIN clientID ON ClientTable.id = InsuranceTable.clientID
INNER JOIN clientID ON InvoicesTable.clientID = ClientTable.id;
```

**Comment by coleifer** [comment]
You can also view the list of views using:

```sql

select name, sql from sqlite_master where type = 'view' order by name
```
