### ISSUE TITLE
Queries return max 1000 rows without subsequent pages

### ISSUE THREAD

**Issue by userkay** [coleifer/sqlite-web#84]
Queries return a maximum of 1000 rows without the ability to browse through subsequent pages

**Comment by coleifer** [comment]
Yes, this is intentional - what do you expect - to crash the browser if you are querying a 1M row table? Can you even properly read and analyze >1000 rows? If you want pagination then add the appropriate LIMIT/OFFSET clauses to the query you are executing.

NOTE: this 1000 row limit is only imposed on the HTML rendering. The export functionality will always export all rows for the query.

**Comment by userkay** [comment]
It's not about loading everything at once but being able to browse through by pages.

I think it pays to answer a bit more politely too.
